# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Claudio Procentese
title: Senior Python Engineer II
email: procentese.claudio@gmail.com
location: Lititz, Pennsylvania, United States
phone: "+1 (717) 203 2433"
github_username: claPro
linkedin_username: claudioprocentese
website: clapro.github.io

# Dark Mode (true/false/never)
darkmode: true

# Additional icon links
additional_links:
  - title: Pdf Download
    icon: far fa-file-pdf
    url: https://clapro.github.io/assets/claudio_procentese_senior_software_engineer.pdf

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Senior Python developer with 10+ years of experience building scalable, high-performance backend systems. I focus on writing clean, maintainable code and designing services that are reliable and easy to work with. I enjoy solving real-world problems with practical, effective solutions and continuously look for ways to streamline development and improve team efficiency.

content:
  - title: Skills
    layout: text
    content: |
      **Languages:** Python (primary), JS, Java, PHP, C  
      **Python Ecosystem:** FastAPI, Django Ninja, Pydantic, Celery, Pandas, NumPy, asyncio  
      **Testing & QA:** Pytest, Selenium, Unit/Integration testing, Test-driven development  
      **Databases:** PostgreSQL, MySQL, MongoDB, MS SQL Server  
      **DevOps & Tools:** Docker, Git, CI/CD (Jenkins, Buddy, GitHub Actions), Linux (shell scripting)  
      **Cloud & Monitoring:** AWS (EC2, S3, Lambda), Datadog (metrics, logs, APM)  
      **Spoken Languages:** English (professional proficiency), Italian (native)

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Protecht Inc
        link: https://protecht.com/
        sub_title: Senior Software Engineer II
        caption: March 2022 – Present
        description: |
          <ul>
            <li>Rebuilt a legacy platform into a scalable, configurable system with modern architecture.</li>
            <li>Improved performance by 80%, maintaining subsecond response times at 400k requests per day.</li>
            <li>Took ownership of the system architecture and backend implementation, from design through deployment.</li>
            <li>Provided technical guidance and code reviews to junior developers, raising code quality and team velocity.</li>
          </ul>

      - layout: left
        title: Nivigroup S.p.A
        link: https://www.nivi.it/
        sub_title: Senior Software Engineer
        caption: March 2014 – February 2023
        description: |
          <ul>
            <li>Developed a Python web app to collect, process, and present financial data used in daily business operations.</li>
            <li>Led backend development for interactive Python projects on multi-touch devices used in surveillance and urban monitoring.</li>
            <li>Handled AWS infrastructure and deployment pipelines to keep services running reliably and updates running smoothly.</li>
          </ul>

      - layout: left
        title: Engineering S.p.A
        link: https://www.eng.it/en
        sub_title: J2EE Developer
        caption: April 2012 – January 2014
        description: |
          <ul>
            <li>Worked on ERP modules supporting public healthcare workflows, including scheduling, payments, and HR.</li>
            <li>Helped modernize the frontend to improve system usability and align with updated standards.</li>
            <li>Handled system debugging and post-issue analysis to ensure continuous service availability.</li>
          </ul>

      - layout: left
        title: Bank Monte dei Paschi di Siena S.p.A
        link: https://www.gruppomps.it/en
        sub_title: J2EE Developer
        caption: June 2011 – March 2012
        description: |
          <ul>
            <li>Developed Java applications using Spring that integrated with an ERP system to generate large batches of banking transaction PDFs.</li>
            <li>Built EJB-based web services to handle data exchange between systems.</li>
            <li>Introduced Spring Batch to improve workload handling, cutting memory usage and speeding up processing times.</li>
          </ul>

      - layout: left
        title: Infocube S.r.l
        link: https://www.infocube.it
        sub_title: J2EE/PHP Developer
        caption: October 2009 – January 2011
        description: |
          <ul>
            <li>Contributed to Java software for rail infrastructure projects, supporting labor and material cost planning.</li>
            <li>Worked on PHP-based e-commerce platforms and websites, focused on usability and backend functionality.</li>
            <li>Improved legacy code stability and reduced disruptions by identifying and fixing long-standing issues.</li>
          </ul>

      - layout: left
        title: Engineering S.r.l
        sub_title: Java Developer
        caption: September 2008 – October 2009
        description: |
          <ul>
            <li>Built a Java/Swing CRM (Asterisk PBX) for a call center, improving how agents managed customer interactions.</li>
            <li>Delivered full-stack features for CakePHP websites with a focus on usability and speed.</li>
            <li>Created a custom eBay listing tool that simplified day-to-day operations for store admins.</li>
          </ul>

      - layout: left
        title: Muir & Associates
        link: https://creditjusticeservices.com
        sub_title: PHP Developer
        caption: January 2005 – January 2007
        description: |
          <ul>
            <li>Worked on a PHP platform for credit recovery, improving process efficiency and user flow.</li>
            <li>Refactored and cleaned up legacy code for easier long-term maintenance.</li>
            <li>Hardened security features in login and access control systems.</li>
          </ul>

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Naples "Federico II"
        caption: 2002
        sub_title: Bachelor of Science in Computer Science
        description: Naples, Italy

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in backend systems and software architecture, I enjoy:
      - Travel
      - Astronomy
      - Music
      - Cats

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
